### ISSUE TITLE
Question on philosophy

### ISSUE THREAD

**Issue by dbuerer** [koderzi/php-github-updater#2]
Curious as to your philosophy and status on this - first glad to see you started this, i was about to created something like this from scratch but thought i'd see if any one else had done it yet...and alas it is here.

How do you expected it to be used?

I see how it appears like you expected to be calling a status heartbeat periodically to find out how it's going....but the install and update process seems to be fairly flat.

Would you consider a few updates?  I'd be happy to make them myself and just put them in a pull request.  But thinking something like this:
1.  Add optional argument to the constructor, maybe something like $initializeOnly, that only set's it up the upgrade but does not call install directly
2. create new public function checkVersion() that checks to see what the latest version is, returns the new version number and release notes
3. manual triggering of update after the above.

I think all the updates could be made without breaking anything

Thoughts?

**Comment by koderzi** [comment]
Hi @dbuerer,

The concept behind the code was to streamline the updating process, leveraging cron for automation. The idea is that upon execution, the script checks for a new version; if an update is necessary, it proceeds, otherwise, it terminates. This simplicity is intentional, but the suggestions for enhancements are insightful.

**Comment by koderzi** [comment]
Upon reviewing, it is indeed necessary to make this update. It may be useful for anyone who wants to update manually. I have revised the code to incorporate this.
